apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbook
  namespace: gitbook
  labels:
    app: gitbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitbook
  template:
    metadata:
      labels:
        app: gitbook
    spec:
      containers:
        - name: gitbook
          image: art.montkim.com/study/my-gitbook:b3523c
          ports:
            - containerPort: 4000
          # args: ["serve"]
